//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elusive.Solodex.Core.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class AddressAttributes
    { }
    [MetadataType(typeof(AddressAttributes))]
    public partial class Address : PersistableModel<Address>
    {
        
        partial void OnContact_IdChanged();
    private System.Guid _Contact_Id;
    public System.Guid Contact_Id
    {
        get
        {
            return _Contact_Id;
        }
        set
        {
            if (_Contact_Id != value)
            {
                _Contact_Id = value;
                OnContact_IdChanged();
                OnPropertyChanged("Contact_Id");
            }
        }
    }
    
        partial void OnNameChanged();
    private string _Name;
    public string Name
    {
        get
        {
            return _Name;
        }
        set
        {
            if (_Name != value)
            {
                _Name = value;
                OnNameChanged();
                OnPropertyChanged("Name");
            }
        }
    }
    
        partial void OnrowversionChanged();
    private byte[] _rowversion;
    public byte[] rowversion
    {
        get
        {
            return _rowversion;
        }
        set
        {
            if (_rowversion != value)
            {
                _rowversion = value;
                OnrowversionChanged();
                OnPropertyChanged("rowversion");
            }
        }
    }
    
        partial void OnStreetChanged();
    private string _Street;
    public string Street
    {
        get
        {
            return _Street;
        }
        set
        {
            if (_Street != value)
            {
                _Street = value;
                OnStreetChanged();
                OnPropertyChanged("Street");
            }
        }
    }
    
        partial void OnCityChanged();
    private string _City;
    public string City
    {
        get
        {
            return _City;
        }
        set
        {
            if (_City != value)
            {
                _City = value;
                OnCityChanged();
                OnPropertyChanged("City");
            }
        }
    }
    
        partial void OnStateChanged();
    private string _State;
    public string State
    {
        get
        {
            return _State;
        }
        set
        {
            if (_State != value)
            {
                _State = value;
                OnStateChanged();
                OnPropertyChanged("State");
            }
        }
    }
    
        partial void OnZipChanged();
    private string _Zip;
    public string Zip
    {
        get
        {
            return _Zip;
        }
        set
        {
            if (_Zip != value)
            {
                _Zip = value;
                OnZipChanged();
                OnPropertyChanged("Zip");
            }
        }
    }
    
    
        partial void OnContactChanged();
    private Contact _Contact;
    public virtual Contact Contact
    {
        get
        {
            return _Contact;
        }
        set
        {
            if (_Contact != value)
            {
                _Contact = value;
                OnContactChanged();
                OnPropertyChanged("Contact");
            }
        }
    }
    
    }
}
