//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elusive.Solodex.Core.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class ApplicationSettingAttributes
    { }
    [MetadataType(typeof(ApplicationSettingAttributes))]
    public partial class ApplicationSetting : PersistableModel<ApplicationSetting>
    {
        
        partial void OnKeyChanged();
    private string _Key;
    public string Key
    {
        get
        {
            return _Key;
        }
        set
        {
            if (_Key != value)
            {
                _Key = value;
                OnKeyChanged();
                OnPropertyChanged("Key");
            }
        }
    }
    
        partial void OnValueChanged();
    private string _Value;
    public string Value
    {
        get
        {
            return _Value;
        }
        set
        {
            if (_Value != value)
            {
                _Value = value;
                OnValueChanged();
                OnPropertyChanged("Value");
            }
        }
    }
    
        partial void OnrowversionChanged();
    private byte[] _rowversion;
    public byte[] rowversion
    {
        get
        {
            return _rowversion;
        }
        set
        {
            if (_rowversion != value)
            {
                _rowversion = value;
                OnrowversionChanged();
                OnPropertyChanged("rowversion");
            }
        }
    }
    
    }
}
