//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elusive.Solodex.Core.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class ContactAttributes
    { }
    [MetadataType(typeof(ContactAttributes))]
    public partial class Contact : PersistableModel<Contact>
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contact()
        {
            this.Addresses = new HashSet<Address>();
        }
    
        
        partial void OnPrefixChanged();
    private string _Prefix;
    public string Prefix
    {
        get
        {
            return _Prefix;
        }
        set
        {
            if (_Prefix != value)
            {
                _Prefix = value;
                OnPrefixChanged();
                OnPropertyChanged("Prefix");
            }
        }
    }
    
        partial void OnFirstChanged();
    private string _First;
    public string First
    {
        get
        {
            return _First;
        }
        set
        {
            if (_First != value)
            {
                _First = value;
                OnFirstChanged();
                OnPropertyChanged("First");
            }
        }
    }
    
        partial void OnMiddleChanged();
    private string _Middle;
    public string Middle
    {
        get
        {
            return _Middle;
        }
        set
        {
            if (_Middle != value)
            {
                _Middle = value;
                OnMiddleChanged();
                OnPropertyChanged("Middle");
            }
        }
    }
    
        partial void OnLastChanged();
    private string _Last;
    public string Last
    {
        get
        {
            return _Last;
        }
        set
        {
            if (_Last != value)
            {
                _Last = value;
                OnLastChanged();
                OnPropertyChanged("Last");
            }
        }
    }
    
        partial void OnSuffixChanged();
    private string _Suffix;
    public string Suffix
    {
        get
        {
            return _Suffix;
        }
        set
        {
            if (_Suffix != value)
            {
                _Suffix = value;
                OnSuffixChanged();
                OnPropertyChanged("Suffix");
            }
        }
    }
    
        partial void OnMobilePhoneChanged();
    private string _MobilePhone;
    public string MobilePhone
    {
        get
        {
            return _MobilePhone;
        }
        set
        {
            if (_MobilePhone != value)
            {
                _MobilePhone = value;
                OnMobilePhoneChanged();
                OnPropertyChanged("MobilePhone");
            }
        }
    }
    
        partial void OnWorkPhoneChanged();
    private string _WorkPhone;
    public string WorkPhone
    {
        get
        {
            return _WorkPhone;
        }
        set
        {
            if (_WorkPhone != value)
            {
                _WorkPhone = value;
                OnWorkPhoneChanged();
                OnPropertyChanged("WorkPhone");
            }
        }
    }
    
        partial void OnGenderChanged();
    private string _Gender;
    public string Gender
    {
        get
        {
            return _Gender;
        }
        set
        {
            if (_Gender != value)
            {
                _Gender = value;
                OnGenderChanged();
                OnPropertyChanged("Gender");
            }
        }
    }
    
        partial void OnDobChanged();
    private Nullable<System.DateTime> _Dob;
    public Nullable<System.DateTime> Dob
    {
        get
        {
            return _Dob;
        }
        set
        {
            if (_Dob != value)
            {
                _Dob = value;
                OnDobChanged();
                OnPropertyChanged("Dob");
            }
        }
    }
    
        partial void OnEmailChanged();
    private string _Email;
    public string Email
    {
        get
        {
            return _Email;
        }
        set
        {
            if (_Email != value)
            {
                _Email = value;
                OnEmailChanged();
                OnPropertyChanged("Email");
            }
        }
    }
    
        partial void OnNotesChanged();
    private string _Notes;
    public string Notes
    {
        get
        {
            return _Notes;
        }
        set
        {
            if (_Notes != value)
            {
                _Notes = value;
                OnNotesChanged();
                OnPropertyChanged("Notes");
            }
        }
    }
    
        partial void OnrowversionChanged();
    private byte[] _rowversion;
    public byte[] rowversion
    {
        get
        {
            return _rowversion;
        }
        set
        {
            if (_rowversion != value)
            {
                _rowversion = value;
                OnrowversionChanged();
                OnPropertyChanged("rowversion");
            }
        }
    }
    
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        partial void OnAddressesChanged();
    private ICollection<Address> _Addresses;
    public virtual ICollection<Address> Addresses
    {
        get
        {
            return _Addresses;
        }
        set
        {
            if (_Addresses != value)
            {
                _Addresses = value;
                OnAddressesChanged();
                OnPropertyChanged("Addresses");
            }
        }
    }
    
    }
}
