//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elusive.Solodex.Core.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class SchemaVersionAttributes
    { }
    [MetadataType(typeof(SchemaVersionAttributes))]
    public partial class SchemaVersion : PersistableModel<SchemaVersion>
    {
        
        partial void OnMajorVersionChanged();
    private int _MajorVersion;
    public int MajorVersion
    {
        get
        {
            return _MajorVersion;
        }
        set
        {
            if (_MajorVersion != value)
            {
                _MajorVersion = value;
                OnMajorVersionChanged();
                OnPropertyChanged("MajorVersion");
            }
        }
    }
    
        partial void OnMinorVersionChanged();
    private int _MinorVersion;
    public int MinorVersion
    {
        get
        {
            return _MinorVersion;
        }
        set
        {
            if (_MinorVersion != value)
            {
                _MinorVersion = value;
                OnMinorVersionChanged();
                OnPropertyChanged("MinorVersion");
            }
        }
    }
    
        partial void OnInstallDateChanged();
    private System.DateTimeOffset _InstallDate;
    public System.DateTimeOffset InstallDate
    {
        get
        {
            return _InstallDate;
        }
        set
        {
            if (_InstallDate != value)
            {
                _InstallDate = value;
                OnInstallDateChanged();
                OnPropertyChanged("InstallDate");
            }
        }
    }
    
    }
}
